### ISSUE TITLE
Corrupt .ogg files on demo site?

### ISSUE THREAD

**Issue by WillCodeCo** [jpemartins/speex.js#12]
I cannot play the sample .ogg files on the http://www.jpemartins.com/speex.js/ demo site.

It appears they are corrupted?

I also have issues when trying to play the oggs when they are downloaded onto my system, in VLC player.

**Comment by jpemartins** [comment]
In Chrome and Firefox (Windows/Linux/OS X) it plays fine according to what I tested. On mobile Firefox also works fine tough some troubles with Chrome. Which browser are you using?

For VLC that behaviour is expected. There is a field called granule_pos that is not updated correctly. This field describes the number of samples per frame. It this is correct the Ogg decoder might ignore which is the case in the opensource libogg.

**Comment by WillCodeCo** [comment]
I experience issues both on Chrome and Firefox running on Ubuntu 12.04

When I click on one of the .ogg links in Firefox I get 'Video can't be
played because the file is corrupt'

In chrome the standard audio player thingo appears but the play button does
nothing.

I have confirmed that I can play '
http://upload.wikimedia.org/wikipedia/en/4/45/ACDC_-_Back_In_Black-sample.ogg'
in both browsers with no problems.

**Comment by jpemartins** [comment]
Yeah that's normal. No browser supports spee when using the default player. That's the reason why we need speex.js. FYI ogg is a container that supports various codecs like CELP, opus and speex for different kinds of streaming.

I thought you meant if you put these demo files inside the decode form in the demo page. If you do so you will hear some sound. Note that these samples files are taken from Speex oficial website.

**Comment by WillCodeCo** [comment]
Sorry for wasting your time, I knew I must have been missing something!
 cheers

**Comment by jpemartins** [comment]
No problem!

Try it out and let me know of any issues :)

**Comment by WillCodeCo** [comment]
I was playing around to see how well it could handle larger files. This
file seemed to break it

http://www.filedropper.com/f2lcapam

I wonder if its just a limitation of it being executed in the browser - it
hits a 'Maximum call stack size exceeded' error

The wav file is 1.3mb 16Khz  (from
http://www.cstr.ed.ac.uk/projects/eustace/down/eustace_wav_f2.zip)  seen at
http://www.cstr.ed.ac.uk/projects/eustace/download.html

Though it seems to work pretty nicely for the smaller audio files, and I
really shouldnt be recording that much sound anyway.

cheers

**Comment by jpemartins** [comment]
That issue was reported in #7. That's why you are getting those errors.

When I created speex.js, the usecase was VoIP applications. The file support is still a bit naive :)
