### ISSUE TITLE
Speex Encoding

### ISSUE THREAD

**Issue by xtremebrat** [jpemartins/speex.js#3]
I am not able to get the project to work . 
Can anyone provide me with a working html file that includes all the javascripts in order to encode a *.wav file.

A simple file to take the existing wav file and specify the output file and store it on the computer .
JPEmartin please help me/

**Comment by wilsonfmn** [comment]
Hi, there!

I'm trying to get this to work with another [library](https://github.com/jwagener/recorder.js/) that gets audio input from my microphone. I'm getting the audio correctly from the first library, but the encoding goes so far as WAV. I tried then using speex.js for encoding, but I'm always getting a an array of length 76 (which i presume it to be the header of an speex file). It doens't matter what I pass to speex: raw audio or wav. Am I missing something?

Thanks in advance.

**Comment by jpemartins** [comment]
Fixed in bedffc214b2780cbdaeda32a65df10d676632359. 

Checkout the [demo app](http://jpemartins.github.io/speex.js/). You can now encode to OGG and download the file later on.
