### ISSUE TITLE
is it possible to convert wav to spx format using javascript?

### ISSUE THREAD

**Issue by vcoder14** [jpemartins/speex.js#4]

**Comment by jpemartins** [comment]
At the moment it only decodes/encodes the speex bytestream, which is then encapsulated in the Ogg container format. Although is this Ogg encapsulation only decoding is implemented ([src/ogg.js](https://github.com/jpemartins/speex.js/blob/master/src/ogg.js) for reference). 

In short, for WAV -> PCM -> Speex it is possible. But WAV -> PCM -> Speex -> OGG no (for now).

**Comment by vcoder14** [comment]
Hi,
 Thanks for your reply! Is it possible to save the  speex  encoded from wav
? if it so could you please help me  to make it so, if i am not bothering
you  much?

**Comment by jpemartins** [comment]
Fixed in bedffc214b2780cbdaeda32a65df10d676632359. 

Checkout the [demo app](http://jpemartins.github.io/speex.js/). You can now encode to OGG and download the file later on.
