### ISSUE TITLE
can't decode speex with ogg, always throw error:notification: More than two wideband layers found. The stream is corrupted. 

### ISSUE THREAD

**Issue by lovemyliwu** [jpemartins/speex.js#6]
i can play on android and pc, why speex.js play throw error

**Comment by lovemyliwu** [comment]
[solved]ok, i decode speex with ogg then encode again on the server side by use speex-tool, after that, speex.js can decode and play now. i don't know what happed to the record side, we use android ndk compile libspeex and record.

**Comment by jpemartins** [comment]
Thanks a lot for trying this out.

Probably you were recording in wideband mode? Speex.js only supports narrow mode :-/ 8000hz sample rate. Either that or something weird in my ogg demux.
